import type { ComponentPropsWithoutRef } from 'react';

import Providers from './providers';

export default function RootLayout ({
  children,
}: ComponentPropsWithoutRef<any>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          { children }
        </Providers>
      </body>
    </html>
  );
}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
