import PropTypes from 'prop-types';

import Providers from './providers';

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          { children }
        </Providers>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
